import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="flex flex-col w-full bg-neutral-300 h-16 top-0 sticky  justify-center items-center">
            <h2 className="text-4xl text-center text-red-600 font-bold">SL Breaking News </h2>
            <div className="animate-marquee whitespace-nowrap ">
              <span className="mx-4 text-lg">Ada Derana</span>
              <span className="mx-4 text-lg">Hiru Tv</span>
              <span className="mx-4 text-lg">Swarnavahini </span>
              <span className="mx-4 text-lg">ITN</span>
            </div>
          </div>
          <NavBar />

          <div className="flex min-h-screen max-w-7xl mx-auto flex-col items-center justify-between mt-9">{children}</div>
        </div>
      </body>
    </html>
  );
}
