import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="w-full bg-neutral-300 h-16 top-0 sticky flex justify-center items-center">
            <h2 className="text-4xl text-center text-red-600 font-bold">SL Breaking News </h2>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
